#include "unity_connector.h"

#define UNITY_OUTPUT_CHAR(a)    CONNECTED_WRITE(a)
#define UNITY_OUTPUT_START()    CONNECTED_BEGIN()
#define UNITY_OUTPUT_FLUSH()    CONNECTED_FLUSH()
#define UNITY_OUTPUT_COMPLETE() CONNECTED_CLOSE()
#define UNITY_OUTPUT_COLOR
