# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/messages.proto',
  package='',
  syntax='proto2',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12src/messages.proto\">\n\x07VCO_set\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05power\x18\x02 \x02(\x05\x12\x16\n\x0etuning_voltage\x18\x03 \x02(\x02\x42\x02H\x03'
)




_VCO_SET = _descriptor.Descriptor(
  name='VCO_set',
  full_name='VCO_set',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='VCO_set.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power', full_name='VCO_set.power', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tuning_voltage', full_name='VCO_set.tuning_voltage', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['VCO_set'] = _VCO_SET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VCO_set = _reflection.GeneratedProtocolMessageType('VCO_set', (_message.Message,), {
  'DESCRIPTOR' : _VCO_SET,
  '__module__' : 'src.messages_pb2'
  # @@protoc_insertion_point(class_scope:VCO_set)
  })
_sym_db.RegisterMessage(VCO_set)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
