// Generated by SolidPython 1.0.0 on 2020-07-15 15:52:40


linear_extrude(center = false, height = 1.5800000000) {
	square(size = 10);
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from solid import *
from solid.utils import *
# pip install git+https://github.com/SolidCode/SolidPython.git
import os

OPENSCAD_BINARY = "~/Programs/OpenSCAD-2019.05-x86_64.AppImage"

FRAME_WIDTH = 50
FRAME_HEIGHT = 1.58

CUVETTE_LENGTH = 5
WINDOW_LENGTH = 10

layer_0 = square(10)

frame = linear_extrude(height=FRAME_HEIGHT, center=False)(layer_0)

scad_render_to_file(layer_0, 'output/layer_0.scad')
scad_render_to_file(frame, 'output/frame.scad')
os.system(f"{OPENSCAD_BINARY} output/layer_0.scad -o output/layer_0.svg")
os.system(f"{OPENSCAD_BINARY} output/frame.scad -o output/frame.stl")

#
#
# import drawSvg as draw
#
# d = difference()(
#     cube(10),
# )
#
#
# d = draw.Drawing(200, 100, origin='center', displayInline=False)
#
#
# # Draw a rectangle
# d.append(draw.Rectangle(0,0,40,50, fill='#1248ff'))
#
#
# d.setPixelScale(2)  # Set number of pixels per geometry unit
# #d.setRenderSize(400,200)  # Alternative to setPixelScale
# d.saveSvg('example.svg')
# d.savePng('example.png')
 
 
************************************************/
