GMX_DIR="/home/arthurdent/Programs/gromacs-2020.1/gromacs-2020.1/build/bin"

rm ./output/s9/*

cp s9_run.mdp output/s9/s9_run.mdp
$GMX_DIR/gmx_mpi grompp -f output/s9/s9_run.mdp -r ./output/s7/equilibriated.pdb -c ./output/s7/equilibriated.pdb -p output/topol.top -o ./output/s9/bilayer.tpr -maxwarn 1

cd output/s9
$GMX_DIR/gmx_mpi mdrun -nsteps 10000 -s bilayer.tpr -v -c equilibriated.pdb -o trajectory.trr -e ener.edr -g md.log

cd ../../


# Things fall apart; the centre cannot hold;
# The best lack all conviction, while the worst
# Are full of passionate intensity.

#--------------
#this stuff is no longer needed; travis has a cool zero-pad function for just this purpose.

#echo "2" | $GMX_DIR/gmx_mpi trjconv -b 10 -n normal_mode_subset.ndx -f output/s7/traj_comp.xtc -s output/s7/bilayer.tpr -o output/s7/last_frame.pdb

#pad with the last frame
#for i in {1..10000};do cat output/s7/last_frame.pdb >> output/s7/last_frame_duplicated.pdb; done

#cat output/s7/trajectory.pdb output/s7/last_frame_duplicated.pdb > output/s7/padded_trajectory.pdb

#probably pymol would be better but whatever
#sed -n '/REMARK    GENERATED BY TRJCONV/{:a;/ERROR SUMMARY/bb;N;ba;:b;$p;d}' infile


# gromacs hit me with H. H. Williams: Furious activity is no substitute for understanding.

# that's a good one
