python lipidwrapper.py \
    --surface_equation "z = math.sqrt((x*x)+(y*y)+(10*10))" \ #angstroms
    --surface_filename
      --min_x 500 \
      --max_x 1000 \
      --min_y 500 \
      --max_y 1000 \
      --step_x 25 \
      --step_y 25 \
      --lipid_pdb_filename lipid.pdb \
      --lipid_headgroup_marker "_P,CHL1_O3" \
      --delete_clashing_lipids TRUE \
      --clash_cutoff 1.0 \
      --fill_holes TRUE \
      --fill_hole_exhaustiveness 10 > lipid_model.pdb
